---
- hosts: lb
  become: true
  remote_user: ec2-user

- hosts: bastion, master, worker
  become: true
  remote_user: ec2-user
  tasks:
    - name: directory
      file: path=/etc/docker/certs.d/{{hostvars['lb'].LB_DNS}}:8443 state=directory
 
    - name: copy ca cert
      copy: src=./certs/ca.crt dest=/etc/docker/certs.d/{{hostvars['lb'].LB_DNS}}:8443/ca.crt

#- hosts: bastion, worker
#  become: true
#  remote_user: ec2-user
#  tasks:
#    - name: remove ca
#      file:
#        path: /etc/kubernetes/pki/{{item}}
#        state: absent
#      with_items: 
#        - ca.crt
#        - ca.key

- hosts: master
  become: true
  remote_user: ec2-user
  tasks:
    - name: copy certs for k8s
      copy:
        src: "{{item}}" 
        dest: /etc/kubernetes/pki/
      with_items:   
        - ./certs/ca.crt
        - ./certs/ca.key


