apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: api
        image: master:31320/api:${BUILD_NUMBER}
        ports:
        - containerPort: 5001
        imagePullPolicy: Always
        
---
apiVersion: v1
kind: Service
metadata:
  name: svc-api
spec:
  type: LoadBalancer
  selector:
    app: flask-api
  ports:
    - port: 80
      targetPort: 5001
