apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: api
        image: master:31320/api:BUILDNUMBER
        ports:
        - containerPort: 5001
        imagePullPolicy: Always
        
---
apiVersion: v1
kind: Service
metadata:
  name: svc-api
spec:
  type: NodeProt
  selector:
    app: flask-api
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 32001
